const {
  MONGODB_URI,
  PORT,
  USER_ACCESS_TOKEN_SECRET,
  USER_REFRESH_TOKEN_SECRET,
  ADMIN_ACCESS_TOKEN_SECRET,
  ADMIN_REFRESH_TOKEN_SECRET,
  ACCESS_TOKEN_EXPIRY,
  REFRESH_TOKEN_EXPIRY,
  CORS_ORIGIN,
} = process.env;

module.exports = {
  MONGODB_URI,
  PORT,
  USER_ACCESS_TOKEN_SECRET,
  USER_REFRESH_TOKEN_SECRET,
  ADMIN_ACCESS_TOKEN_SECRET,
  ADMIN_REFRESH_TOKEN_SECRET,
  ACCESS_TOKEN_EXPIRY,
  REFRESH_TOKEN_EXPIRY,
  CORS_ORIGIN,
};
