services:
  valkey:
    image: valkey/valkey
    ports:
      - 6379:6379

  qdrant:
    image: qdrant/qdrant
    ports:
      - 6333:6333
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data:
